Repository arillso/ansible.restic, pull requests merged in 2020-11, with the labels that each got.

#24 doc: add example for backup syntax
  README.md
Labels: documentation, enhancement

#22 fix: error when trying to re-initialize b2 repository
  tasks/configure.yml
Labels: bug

#27 change: bump default restic version to `0.11.0`
  README.md
  defaults/main.yml
  molecule/default/test_restic/tasks/test_backup_files.yml
Labels: dependencies

#28 change: backups can be defined as dicts
  README.md
  molecule/default/playbook.yml
  molecule/default/test_restic/tasks/test_backup_files.yml
  tasks/distribution/Linux.yml
Labels: documentation, enhancement
